# network-and-iam.yml
AWSTemplateFormatVersion: '2010-09-09'
Description: "VPC, subnets, security group, and IAM roles for ETL project"

Parameters:
  UniqueSuffix:
    Type: String
    Description: "Unique suffix for resource names"

Resources:
  IACVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub 'iac-vpc-${UniqueSuffix}'

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub 'iac-igw-${UniqueSuffix}'

  VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref IACVPC
      InternetGatewayId: !Ref InternetGateway

  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref IACVPC
      Tags:
        - Key: Name
          Value: !Sub 'iac-public-rt-${UniqueSuffix}'

  PublicRoute:
    Type: AWS::EC2::Route
    DependsOn: VPCGatewayAttachment
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref InternetGateway

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref IACVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: !Select [0, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub 'iac-subnet-1-${UniqueSuffix}'

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref IACVPC
      CidrBlock: 10.0.2.0/24
      AvailabilityZone: !Select [1, !GetAZs '']
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub 'iac-subnet-2-${UniqueSuffix}'

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet1
      RouteTableId: !Ref PublicRouteTable

  Subnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref Subnet2
      RouteTableId: !Ref PublicRouteTable

  BatchSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'Security group for Batch Fargate containers'
      VpcId: !Ref IACVPC
      SecurityGroupIngress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

  BatchJobRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'BatchJobRole-IAC-Project-${UniqueSuffix}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: 'BatchJobPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:GetObject'
                  - 's3:PutObject'
                Resource: '*'

  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'ecsTaskExecutionRole-${UniqueSuffix}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:
  VPCId:
    Value: !Ref IACVPC
  Subnet1Id:
    Value: !Ref Subnet1
  Subnet2Id:
    Value: !Ref Subnet2
  BatchSecurityGroupId:
    Value: !Ref BatchSecurityGroup
  BatchJobRoleArn:
    Value: !GetAtt BatchJobRole.Arn
  ECSExecutionRoleArn:
    Value: !GetAtt ECSExecutionRole.Arn
